### ISSUE TITLE
May I use "opus useinbandfec"?

### ISSUE THREAD

**Issue by iw0red** [sm0svx/svxlink#435] opened 2019-01-20 16:02 UTC
Hi everyone,
may I use "opus useinbandfec" both for reflector and for remotetrx?
Thanks in advance,
73 Marco IW0RED.

**Comment by iw0red** [comment] 2019-02-11 09:59
Thanks ....

**Comment by sm0svx** [comment] 2019-07-15 17:50
Duplicate of #451

**Closed by sm0svx** 2019-07-15 17:50 UTC
