### ISSUE TITLE
Multiple UDP frame losts and heartbeat timeouts - but why?

### ISSUE THREAD

**Issue by DF2HS** [sm0svx/svxlink#540] opened 2021-03-28 10:40 UTC
Hi

We have about 12 repeaters hanging on a svx reflector server for coupling etc.
We have some repeaters in the same talkgroup, some in their own groups. 
For reading out ham news we couple some repeaters together at some times.

So far, so good. The repeater A changes its talkgroup to the talkgroup of repeater B.

But we are discovering multiple errors like heartbeat timeouts or UDP packet drops or losses.

We tried different configurations, we changed the hardware of the server, tried the network connection via optical fibre, RF (5GHz links), copper cable or LTE.

With all network types the problem occurs. Since now we do not know why. We think it´s a software issue.

So maybe some of you have also discovered errors like this in their logs:

Repeater log:

> Sun Mar 28 11:09:55 2021: *** ERROR: Heartbeat timeout. Disconnecting from (IP)...
> Sun Mar 28 11:09:55 2021: myremoterx: Disconnected from remote receiver (IP): Locally ordered disconnect

Remote Rx log:

> Sun Mar 28 11:09:55 2021: myrepeater1: Client disconnected: (IP)
> Sun Mar 28 11:10:09 2021: *** ERROR: Heartbeat timeout in NetUplink (myrepeater)
> Sun Mar 28 11:10:09 2021: myrepeater2: Client disconnected: (IP)

Another problem are UDP frame losts.

Server log:

> 28.03.2021 11:01:55: myrepeater: UDP frame(s) lost. Expected seq=39511. Received                                     seq=39512
> 28.03.2021 11:01:55: myrepeater: UDP frame(s) lost. Expected seq=39517. Received                                     seq=39518
> 28.03.2021 11:01:55: myrepeater: UDP frame(s) lost. Expected seq=39520. Received                                     seq=39521
> 28.03.2021 11:01:56: myrepeater: UDP frame(s) lost. Expected seq=39569. Received                                     seq=39570

These frame lost errors are in the server log, but not in the repeater log.
Then there are also errors which are only in the repeater log, but not in  the server log.

I am very confused and have no idea.

Most of the repeaters are using a current svx version, some of them are running an older version with protocol version 1.0. But so far everything is fine and works.

I have no idea what to check next... so could please someone be so kind and help me?

73
Sandy DF2HS

**Comment by sm0svx** [comment] 2021-06-27 12:10
If you have not already done so you should try to ask at groups.io. It is highly unlikely that this problem is caused by a bug in SvxLink. I'm closing this issue for now. Reopen it if you find proof that it is indeed a software problem.

**Closed by sm0svx** 2021-06-27 12:10 UTC
