### ISSUE TITLE
current cmake issue debian jessie

### ISSUE THREAD

**Issue by rneese45** [sm0svx/svxlink#144] opened 2015-06-01 14:17 UTC
make install failes with following errors

-- Setting owner of /var/spool/svxlink/qso_recorder to svxlink.daemon...
/bin/chown: invalid user: ‘svxlink.daemon’
CMake Error at svxlink/svxlink/cmake_install.cmake:100 (MESSAGE):
  Error while changing owner of file /var/spool/svxlink/qso_recorder
Call Stack (most recent call first):
  svxlink/cmake_install.cmake:38 (include)
  cmake_install.cmake:41 (include)

Makefile:66: recipe for target 'install' failed
make: *** [install] Error 1
root@kb3vgw-repeater:/usr/src/svxlink-14.08.1/src/build#

**Comment by pe1chl** [comment] 2015-06-02 09:07
Please read the installation instructions on the WiKi when installing from source.
https://github.com/sm0svx/svxlink/wiki/InstallationInstructions

**Comment by rneese45** [comment] 2015-06-03 21:14
I followed that to the T and doted the i's and I still get the same error on debian jessie armhf

**Comment by rneese45** [comment] 2015-06-03 21:16
/bin/chown: invalid user: ‘svxlink.daemon’
CMake Error at svxlink/svxlink/cmake_install.cmake:100 (MESSAGE):
Error while changing owner of file /var/spool/svxlink/qso_recorder
Call Stack (most recent call first):
svxlink/cmake_install.cmake:38 (include)
cmake_install.cmake:41 (include)

Makefile:66: recipe for target 'install' failed
make: *** [install] Error 1
root@kb3vgw-repeater:/usr/src/svxlink-14.08.1/src/build#

fresh install today and ran it again per the wiki page it still fails

**Comment by rneese45** [comment] 2015-06-03 21:45
here is the step by step 

apt-get install -y g++ make cmake libsigc++-2.0-dev libgsm1-dev libpopt-dev libgcrypt11-dev \
			libspeex-dev libasound2-dev alsa-utils vorbis-tools sox libsox-fmt-mp3 sqlite3 \
			unzip opus-tools tcl8.6-dev 

	mkdir /usr/src/downloads
	cd /usr/src/downloads
	wget https://github.com/sm0svx/svxlink/archive/14.08.1.tar.gz
	tar xvzf 14.08.1.tar.gz -C /usr/src/
	cd /usr/src/svxlink-14.08.1/src

        mkdir build && cd build

root@kb3vgw-repeater:/usr/src/svxlink-14.08.1/src/build# cmake -DCMAKE_INSTALL_PREFIX=/usr -DSYSCONF_INSTALL_DIR=/etc -DLOCAL_STATE_DIR=/var -DUSE_QT=NO ..
-- Reading versions file...
-- Found components for RT
-- RT_INCLUDES = /usr/include
-- RT_LIBRARIES     = /usr/lib/arm-linux-gnueabihf/librt.so
-- Could NOT find Opus (missing:  Opus_LIBRARY Opus_INCLUDE_DIR)
-- Found ALSA 1.0.28
-- checking for module 'popt'
--   found popt, version 1.16
-- Found Popt: /usr/lib/arm-linux-gnueabihf/libpopt.so
-- Found GCrypt: /usr/lib/arm-linux-gnueabihf/libgcrypt.so
-- Found Popt: /usr/lib/arm-linux-gnueabihf/libpopt.so
-- Found Tclsh: /usr/bin/tclsh8.6 (found version "8.6")
-- Found TCL: /usr/lib/arm-linux-gnueabihf/libtcl8.6.so
-- Could NOT find TCLTK (missing:  TK_LIBRARY TK_INCLUDE_PATH)
-- Could NOT find TK (missing:  TK_LIBRARY TK_INCLUDE_PATH)
-- Found components for DL
-- DL_INCLUDES = /usr/include
-- DL_LIBRARIES     = /usr/lib/arm-linux-gnueabihf/libdl.so
-- Could NOT find TCLTK (missing:  TK_LIBRARY TK_INCLUDE_PATH)
-- Could NOT find TK (missing:  TK_LIBRARY TK_INCLUDE_PATH)
-- Found Popt: /usr/lib/arm-linux-gnueabihf/libpopt.so
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/svxlink-14.08.1/src/build


root@kb3vgw-repeater:/usr/src/svxlink-14.08.1/src/build# make
[  0%] [  0%] [  1%] Scanning dependencies of target asynccore
Generating ../../../include/version/SVXLINK.h
Generating ../../../include/version/SVXLINK.h
Generating ../../include/version/SVXLINK.h
[  3%] [  3%] Scanning dependencies of target trx
Generating ../../../include/version/MODULE_HELP.h
Generating ../../../include/version/MODULE_PARROT.h
[  3%] Scanning dependencies of target ModuleHelp
Scanning dependencies of target ModuleParrot
Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncApplication.cpp.o
[  5%] [  5%] Building CXX object svxlink/modules/help/CMakeFiles/ModuleHelp.dir/ModuleHelp.cpp.o
Building CXX object svxlink/modules/parrot/CMakeFiles/ModuleParrot.dir/ModuleParrot.cpp.o
[  5%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/ToneDetector.cpp.o
[  6%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncFdWatch.cpp.o
[  7%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncTimer.cpp.o
Linking CXX shared module ../../../lib/ModuleHelp.so
[  8%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/SwDtmfDecoder.cpp.o
[  8%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncIpAddress.cpp.o
[  8%] Built target ModuleHelp
[  9%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/Rx.cpp.o
Linking CXX shared module ../../../lib/ModuleParrot.so
[  9%] Built target ModuleParrot
[  9%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/LocalRx.cpp.o
[ 10%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncDnsLookup.cpp.o
[ 11%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncTcpClient.cpp.o
[ 11%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncUdpSocket.cpp.o
[ 13%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncTcpServer.cpp.o
[ 13%] Generating ../../../include/version/MODULE_TCL.h
Scanning dependencies of target ModuleTcl
[ 14%] Building CXX object svxlink/modules/tcl/CMakeFiles/ModuleTcl.dir/ModuleTcl.cpp.o
[ 14%] Generating ../../../include/version/MODULE_DTMF_REPEATER.h
Scanning dependencies of target ModuleDtmfRepeater
[ 15%] Building CXX object svxlink/modules/dtmf_repeater/CMakeFiles/ModuleDtmfRepeater.dir/ModuleDtmfRepeater.cpp.o
[ 15%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncTcpConnection.cpp.o
Linking CXX shared module ../../../lib/ModuleTcl.so
[ 16%] Built target ModuleTcl
[ 17%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncConfig.cpp.o
Linking CXX shared module ../../../lib/ModuleDtmfRepeater.so
[ 18%] Built target ModuleDtmfRepeater
[ 19%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncSerial.cpp.o
[ 20%] Generating ../../../include/version/MODULE_METARINFO.h
Scanning dependencies of target ModuleMetarInfo
[ 21%] Building CXX object svxlink/modules/metarinfo/CMakeFiles/ModuleMetarInfo.dir/ModuleMetarInfo.cpp.o
[ 22%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/SquelchVox.cpp.o
[ 22%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncSerialDevice.cpp.o
[ 23%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncFileReader.cpp.o
[ 25%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/SigLevDetNoise.cpp.o
[ 25%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/NetRx.cpp.o
[ 26%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncAtTimer.cpp.o
[ 26%] Building CXX object async/core/CMakeFiles/asynccore.dir/AsyncExec.cpp.o
[ 27%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/Voter.cpp.o
[ 27%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/Tx.cpp.o
Linking CXX shared library ../../lib/libasynccore.so
[ 27%] Built target asynccore
[ 28%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/LocalTx.cpp.o
Scanning dependencies of target asynccpp
[ 29%] Building CXX object async/cpp/CMakeFiles/asynccpp.dir/AsyncCppApplication.cpp.o
[ 29%] Building CXX object async/cpp/CMakeFiles/asynccpp.dir/AsyncCppDnsLookupWorker.cpp.o
Linking CXX shared module ../../../lib/ModuleMetarInfo.so
[ 29%] Built target ModuleMetarInfo
[ 30%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/DtmfEncoder.cpp.o
Scanning dependencies of target asyncaudio
Linking CXX shared library ../../lib/libasynccpp.so
Scanning dependencies of target locationinfo
[ 30%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioSource.cpp.o
[ 31%] Building CXX object locationinfo/CMakeFiles/locationinfo.dir/LocationInfo.cpp.o
[ 31%] Built target asynccpp
[ 31%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/NetTx.cpp.o
[ 32%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioSink.cpp.o
[ 32%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioProcessor.cpp.o
[ 33%] Building CXX object locationinfo/CMakeFiles/locationinfo.dir/AprsTcpClient.cpp.o
[ 34%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioCompressor.cpp.o
[ 35%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioFilter.cpp.o
[ 35%] Building C object async/audio/CMakeFiles/asyncaudio.dir/fidlib.c.o
[ 36%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/NetTrxTcpClient.cpp.o
[ 38%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/DtmfDecoder.cpp.o
[ 39%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioDevice.cpp.o
[ 39%] Building CXX object locationinfo/CMakeFiles/locationinfo.dir/AprsUdpClient.cpp.o
[ 39%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/HwDtmfDecoder.cpp.o
[ 40%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/S54sDtmfDecoder.cpp.o
[ 41%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioIO.cpp.o
[ 41%] Linking CXX static library liblocationinfo.a
[ 41%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioSplitter.cpp.o
[ 42%] [ 42%] Built target locationinfo
Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioDelayLine.cpp.o
[ 42%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioSelector.cpp.o
[ 43%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioMixer.cpp.o
Building CXX object svxlink/trx/CMakeFiles/trx.dir/PttCtrl.cpp.o
[ 44%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/MultiTx.cpp.o
[ 45%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/SigLevDetTone.cpp.o
[ 46%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioFifo.cpp.o
[ 46%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioPacer.cpp.o
[ 46%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/Sel5Decoder.cpp.o
[ 47%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioReader.cpp.o
[ 48%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioDecimator.cpp.o
[ 50%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/SwSel5Decoder.cpp.o
[ 50%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioInterpolator.cpp.o
[ 51%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/SquelchEvDev.cpp.o
[ 52%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioDecoder.cpp.o
[ 52%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioEncoder.cpp.o
[ 52%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/Macho.cpp.o
[ 53%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioEncoderS16.cpp.o
[ 54%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/SquelchGpio.cpp.o
[ 55%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioDecoderS16.cpp.o
[ 55%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/Ptt.cpp.o
[ 55%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioEncoderGsm.cpp.o
[ 56%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/PttGpio.cpp.o
[ 57%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioDecoderGsm.cpp.o
[ 58%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioRecorder.cpp.o
[ 58%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioDeviceFactory.cpp.o
[ 59%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioJitterFifo.cpp.o
[ 60%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/PttSerialPin.cpp.o
[ 60%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/Pty.cpp.o
[ 60%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioDeviceUDP.cpp.o
[ 61%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioEncoderSpeex.cpp.o
[ 63%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioDecoderSpeex.cpp.o
[ 64%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/PttPty.cpp.o
[ 65%] Building CXX object svxlink/trx/CMakeFiles/trx.dir/PtyDtmfDecoder.cpp.o
[ 65%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioDeviceAlsa.cpp.o
[ 66%] Building CXX object async/audio/CMakeFiles/asyncaudio.dir/AsyncAudioDeviceOSS.cpp.o
Linking CXX static library libtrx.a
[ 66%] Built target trx
Linking CXX shared library ../../lib/libasyncaudio.so
[ 66%] Built target asyncaudio
Scanning dependencies of target AsyncCppApplication_demo
Scanning dependencies of target AsyncConfig_demo
Scanning dependencies of target AsyncAudioIO_demo
Scanning dependencies of target AsyncAtTimer_demo
[ 66%] Building CXX object async/demo/CMakeFiles/AsyncConfig_demo.dir/AsyncConfig_demo.cpp.o
[ 67%] [ 68%] [ 68%] Building CXX object async/demo/CMakeFiles/AsyncCppApplication_demo.dir/AsyncCppApplication_demo.cpp.o
Building CXX object async/demo/CMakeFiles/AsyncAtTimer_demo.dir/AsyncAtTimer_demo.cpp.o
Building CXX object async/demo/CMakeFiles/AsyncAudioIO_demo.dir/AsyncAudioIO_demo.cpp.o
Linking CXX executable AsyncCppApplication_demo
[ 68%] Built target AsyncCppApplication_demo
Scanning dependencies of target AsyncDnsLookup_demo
[ 69%] Building CXX object async/demo/CMakeFiles/AsyncDnsLookup_demo.dir/AsyncDnsLookup_demo.cpp.o
Linking CXX executable AsyncAtTimer_demo
Linking CXX executable AsyncConfig_demo
Linking CXX executable AsyncAudioIO_demo
[ 69%] Built target AsyncAtTimer_demo
Scanning dependencies of target AsyncExec_demo
[ 69%] Built target AsyncConfig_demo
[ 69%] Scanning dependencies of target AsyncFdWatch_demo
Building CXX object async/demo/CMakeFiles/AsyncExec_demo.dir/AsyncExec_demo.cpp.o
[ 69%] Built target AsyncAudioIO_demo
Scanning dependencies of target AsyncSerial_demo
[ 70%] [ 70%] Building CXX object async/demo/CMakeFiles/AsyncFdWatch_demo.dir/AsyncFdWatch_demo.cpp.o
Building CXX object async/demo/CMakeFiles/AsyncSerial_demo.dir/AsyncSerial_demo.cpp.o
Linking CXX executable AsyncDnsLookup_demo
[ 70%] Built target AsyncDnsLookup_demo
Scanning dependencies of target AsyncTcpClient_demo
Linking CXX executable AsyncFdWatch_demo
Linking CXX executable AsyncSerial_demo
[ 71%] Building CXX object async/demo/CMakeFiles/AsyncTcpClient_demo.dir/AsyncTcpClient_demo.cpp.o
[ 71%] Built target AsyncFdWatch_demo
Scanning dependencies of target AsyncTcpServer_demo
Linking CXX executable AsyncExec_demo
[ 72%] [ 72%] Built target AsyncSerial_demo
Building CXX object async/demo/CMakeFiles/AsyncTcpServer_demo.dir/AsyncTcpServer_demo.cpp.o
Scanning dependencies of target AsyncTimer_demo
[ 72%] Building CXX object async/demo/CMakeFiles/AsyncTimer_demo.dir/AsyncTimer_demo.cpp.o
[ 72%] Built target AsyncExec_demo
Scanning dependencies of target AsyncUdpSocket_demo
[ 73%] Building CXX object async/demo/CMakeFiles/AsyncUdpSocket_demo.dir/AsyncUdpSocket_demo.cpp.o
Linking CXX executable AsyncTimer_demo
Linking CXX executable AsyncTcpClient_demo
[ 73%] Built target AsyncTimer_demo
Scanning dependencies of target echolib
Linking CXX executable AsyncUdpSocket_demo
[ 75%] Building CXX object echolib/CMakeFiles/echolib.dir/EchoLinkDirectory.cpp.o
[ 75%] Built target AsyncTcpClient_demo
[ 76%] Building CXX object echolib/CMakeFiles/echolib.dir/EchoLinkQso.cpp.o
Linking CXX executable AsyncTcpServer_demo
[ 76%] Built target AsyncUdpSocket_demo
[ 76%] Building CXX object echolib/CMakeFiles/echolib.dir/rtpacket.cpp.o
[ 76%] Built target AsyncTcpServer_demo
[ 77%] Building CXX object echolib/CMakeFiles/echolib.dir/EchoLinkDispatcher.cpp.o
Scanning dependencies of target svxlink
[ 78%] Building CXX object svxlink/svxlink/CMakeFiles/svxlink.dir/MsgHandler.cpp.o
[ 79%] Building CXX object svxlink/svxlink/CMakeFiles/svxlink.dir/Module.cpp.o
[ 80%] Generating ../../include/version/REMOTE_TRX.h
Scanning dependencies of target remotetrx
[ 80%] Building CXX object svxlink/remotetrx/CMakeFiles/remotetrx.dir/TrxHandler.cpp.o
[ 81%] Building CXX object svxlink/remotetrx/CMakeFiles/remotetrx.dir/Uplink.cpp.o
[ 81%] Generating ../../include/version/SIGLEV_DET_CAL.h
Scanning dependencies of target siglevdetcal
[ 82%] Building CXX object svxlink/siglevdetcal/CMakeFiles/siglevdetcal.dir/siglevdetcal.cpp.o
[ 83%] Building CXX object svxlink/remotetrx/CMakeFiles/remotetrx.dir/NetUplink.cpp.o
[ 83%] Building CXX object svxlink/svxlink/CMakeFiles/svxlink.dir/Logic.cpp.o
[ 84%] Building CXX object echolib/CMakeFiles/echolib.dir/EchoLinkStationData.cpp.o
[ 84%] Building CXX object echolib/CMakeFiles/echolib.dir/EchoLinkProxy.cpp.o
Linking CXX executable ../../bin/siglevdetcal
[ 84%] Built target siglevdetcal
[ 85%] Building CXX object svxlink/svxlink/CMakeFiles/svxlink.dir/SimplexLogic.cpp.o
[ 86%] Building CXX object echolib/CMakeFiles/echolib.dir/EchoLinkDirectoryCon.cpp.o
[ 86%] Building C object echolib/CMakeFiles/echolib.dir/md5.c.o
[ 88%] Building CXX object svxlink/svxlink/CMakeFiles/svxlink.dir/RepeaterLogic.cpp.o
[ 88%] Building CXX object svxlink/remotetrx/CMakeFiles/remotetrx.dir/RfUplink.cpp.o
Linking CXX shared library ../lib/libecholib.so
[ 89%] [ 89%] Built target echolib
Building CXX object svxlink/remotetrx/CMakeFiles/remotetrx.dir/NetTrxAdapter.cpp.o
[ 90%] Building CXX object svxlink/remotetrx/CMakeFiles/remotetrx.dir/remotetrx.cpp.o
Scanning dependencies of target EchoLinkDirectory_demo
[ 91%] Building CXX object echolib/CMakeFiles/EchoLinkDirectory_demo.dir/EchoLinkDirectory_demo.cpp.o
[ 91%] Building CXX object svxlink/svxlink/CMakeFiles/svxlink.dir/EventHandler.cpp.o
[ 92%] Building CXX object svxlink/svxlink/CMakeFiles/svxlink.dir/LinkManager.cpp.o
Linking CXX executable EchoLinkDirectory_demo
[ 92%] Built target EchoLinkDirectory_demo
Linking CXX executable ../../bin/remotetrx
[ 92%] Building CXX object svxlink/svxlink/CMakeFiles/svxlink.dir/CmdParser.cpp.o
[ 92%] Built target remotetrx
[ 93%] Building CXX object svxlink/svxlink/CMakeFiles/svxlink.dir/QsoRecorder.cpp.o
Scanning dependencies of target EchoLinkDispatcher_demo
[ 93%] Building CXX object echolib/CMakeFiles/EchoLinkDispatcher_demo.dir/EchoLinkDispatcher_demo.cpp.o
Scanning dependencies of target EchoLinkQso_demo
[ 94%] Building CXX object echolib/CMakeFiles/EchoLinkQso_demo.dir/EchoLinkQso_demo.cpp.o
Linking CXX executable EchoLinkDispatcher_demo
[ 94%] Built target EchoLinkDispatcher_demo
[ 95%] Building CXX object svxlink/svxlink/CMakeFiles/svxlink.dir/svxlink.cpp.o
Linking CXX executable EchoLinkQso_demo
[ 95%] Built target EchoLinkQso_demo
[ 95%] Building CXX object svxlink/svxlink/CMakeFiles/svxlink.dir/DtmfDigitHandler.cpp.o
Scanning dependencies of target echolib_test
[ 95%] [ 96%] Generating ../../../include/version/MODULE_ECHOLINK.h
Building CXX object echolib/CMakeFiles/echolib_test.dir/echolib_test.cpp.o
Scanning dependencies of target ModuleEchoLink
[ 97%] Building CXX object svxlink/modules/echolink/CMakeFiles/ModuleEchoLink.dir/ModuleEchoLink.cpp.o
[ 98%] Building CXX object echolib/CMakeFiles/echolib_test.dir/EchoLinkQsoTest.cpp.o
[ 98%] Building CXX object svxlink/modules/echolink/CMakeFiles/ModuleEchoLink.dir/QsoImpl.cpp.o
Linking CXX executable ../../bin/svxlink
[ 98%] Built target svxlink
Linking CXX executable echolib_test
[ 98%] Built target echolib_test
Linking CXX shared module ../../../lib/ModuleEchoLink.so
[100%] Built target ModuleEchoLink


root@kb3vgw-repeater:/usr/src/svxlink-14.08.1/src/build# make install
[  9%] Built target asynccore
[ 10%] Built target asynccpp
[ 31%] Built target asyncaudio
[ 31%] Built target AsyncAtTimer_demo
[ 32%] Built target AsyncAudioIO_demo
[ 32%] Built target AsyncConfig_demo
[ 33%] Built target AsyncCppApplication_demo
[ 34%] Built target AsyncDnsLookup_demo
[ 34%] Built target AsyncExec_demo
[ 35%] Built target AsyncFdWatch_demo
[ 35%] Built target AsyncSerial_demo
[ 36%] Built target AsyncTcpClient_demo
[ 38%] Built target AsyncTcpServer_demo
[ 38%] Built target AsyncTimer_demo
[ 39%] Built target AsyncUdpSocket_demo
[ 44%] Built target echolib
[ 45%] Built target EchoLinkDirectory_demo
[ 45%] Built target EchoLinkDispatcher_demo
[ 46%] Built target EchoLinkQso_demo
[ 48%] Built target echolib_test
[ 51%] Built target locationinfo
[ 72%] Built target trx
[ 80%] Built target svxlink
[ 82%] Built target ModuleHelp
[ 84%] Built target ModuleParrot
[ 86%] Built target ModuleEchoLink
[ 89%] Built target ModuleTcl
[ 91%] Built target ModuleDtmfRepeater
[ 93%] Built target ModuleMetarInfo
[ 98%] Built target remotetrx
[100%] Built target siglevdetcal
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/lib/libasynccore.so.1.3.1
-- Installing: /usr/lib/libasynccore.so.1.3
-- Installing: /usr/lib/libasynccore.so
-- Installing: /usr/include/svxlink/AsyncApplication.h
-- Installing: /usr/include/svxlink/AsyncFdWatch.h
-- Installing: /usr/include/svxlink/AsyncTimer.h
-- Installing: /usr/include/svxlink/AsyncIpAddress.h
-- Installing: /usr/include/svxlink/AsyncTcpClient.h
-- Installing: /usr/include/svxlink/AsyncDnsLookup.h
-- Installing: /usr/include/svxlink/AsyncUdpSocket.h
-- Installing: /usr/include/svxlink/AsyncTcpServer.h
-- Installing: /usr/include/svxlink/AsyncTcpConnection.h
-- Installing: /usr/include/svxlink/AsyncConfig.h
-- Installing: /usr/include/svxlink/AsyncSerial.h
-- Installing: /usr/include/svxlink/AsyncFileReader.h
-- Installing: /usr/include/svxlink/AsyncAtTimer.h
-- Installing: /usr/include/svxlink/AsyncExec.h
-- Installing: /usr/lib/libasynccpp.so.1.3.1
-- Installing: /usr/lib/libasynccpp.so.1.3
-- Installing: /usr/lib/libasynccpp.so
-- Removed runtime path from "/usr/lib/libasynccpp.so.1.3.1"
-- Installing: /usr/include/svxlink/AsyncCppApplication.h
-- Installing: /usr/lib/libasyncaudio.so.1.3.1
-- Installing: /usr/lib/libasyncaudio.so.1.3
-- Installing: /usr/lib/libasyncaudio.so
-- Removed runtime path from "/usr/lib/libasyncaudio.so.1.3.1"
-- Installing: /usr/include/svxlink/AsyncAudioSource.h
-- Installing: /usr/include/svxlink/AsyncAudioSink.h
-- Installing: /usr/include/svxlink/AsyncAudioProcessor.h
-- Installing: /usr/include/svxlink/AsyncAudioClipper.h
-- Installing: /usr/include/svxlink/AsyncAudioCompressor.h
-- Installing: /usr/include/svxlink/AsyncAudioFilter.h
-- Installing: /usr/include/svxlink/AsyncSigCAudioSink.h
-- Installing: /usr/include/svxlink/AsyncSigCAudioSource.h
-- Installing: /usr/include/svxlink/AsyncAudioIO.h
-- Installing: /usr/include/svxlink/AsyncAudioSplitter.h
-- Installing: /usr/include/svxlink/AsyncAudioDelayLine.h
-- Installing: /usr/include/svxlink/AsyncAudioValve.h
-- Installing: /usr/include/svxlink/AsyncAudioAmp.h
-- Installing: /usr/include/svxlink/AsyncAudioSelector.h
-- Installing: /usr/include/svxlink/AsyncAudioPassthrough.h
-- Installing: /usr/include/svxlink/AsyncAudioMixer.h
-- Installing: /usr/include/svxlink/AsyncAudioFifo.h
-- Installing: /usr/include/svxlink/AsyncAudioDebugger.h
-- Installing: /usr/include/svxlink/AsyncAudioPacer.h
-- Installing: /usr/include/svxlink/AsyncAudioReader.h
-- Installing: /usr/include/svxlink/AsyncAudioDecimator.h
-- Installing: /usr/include/svxlink/AsyncAudioInterpolator.h
-- Installing: /usr/include/svxlink/AsyncAudioStreamStateDetector.h
-- Installing: /usr/include/svxlink/AsyncAudioEncoder.h
-- Installing: /usr/include/svxlink/AsyncAudioDecoder.h
-- Installing: /usr/include/svxlink/AsyncAudioRecorder.h
-- Installing: /usr/include/svxlink/AsyncAudioJitterFifo.h
-- Installing: /usr/include/svxlink/AsyncAudioDeviceFactory.h
-- Installing: /usr/include/svxlink/AsyncAudioDevice.h
-- Installing: /usr/include/svxlink/common.h
-- Installing: /usr/lib/libecholib.so.1.3.1
-- Installing: /usr/lib/libecholib.so.1.3
-- Installing: /usr/lib/libecholib.so
-- Removed runtime path from "/usr/lib/libecholib.so.1.3.1"
-- Installing: /usr/include/svxlink/EchoLinkDirectory.h
-- Installing: /usr/include/svxlink/EchoLinkDispatcher.h
-- Installing: /usr/include/svxlink/EchoLinkQso.h
-- Installing: /usr/include/svxlink/EchoLinkStationData.h
-- Installing: /usr/include/svxlink/EchoLinkProxy.h
-- Installing: /usr/bin/svxlink
-- Removed runtime path from "/usr/bin/svxlink"
-- Installing: /etc/svxlink/svxlink.d
-- Installing: /var/spool/svxlink/qso_recorder
-- Setting owner of /var/spool/svxlink/qso_recorder to svxlink.daemon...
/bin/chown: invalid user: ‘svxlink.daemon’
CMake Error at svxlink/svxlink/cmake_install.cmake:100 (MESSAGE):
  Error while changing owner of file /var/spool/svxlink/qso_recorder
Call Stack (most recent call first):
  svxlink/cmake_install.cmake:38 (include)
  cmake_install.cmake:41 (include)


Makefile:66: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by pe1chl** [comment] 2015-06-03 21:51
You did not take this (quoted from the docs) into account:

You will also need to create a system user called svxlink before installing if it does not already exist. The daemon group is also needed so if that does not exist it must also be created.

**Comment by rneese45** [comment] 2015-06-03 22:01
I am willing to put this arm board on a dmz port and let some one in and look and test.

**Comment by rneese45** [comment] 2015-06-03 22:42
I just tried the git repo version same error 
-- Setting owner of /var/spool/svxlink/qso_recorder to svxlink.daemon...
/bin/chown: invalid user: ‘svxlink.daemon’
CMake Error at svxlink/svxlink/cmake_install.cmake:100 (MESSAGE):
  Error while changing owner of file /var/spool/svxlink/qso_recorder
Call Stack (most recent call first):
  svxlink/cmake_install.cmake:38 (include)
  cmake_install.cmake:41 (include)

**Comment by rneese45** [comment] 2015-06-04 01:50
This should be done in the install script. Also I am working on system
startup scripts and I will be looking at working on Debian pkgs

**Comment by rneese45** [comment] 2015-06-04 03:39
you should add a line to the wiki for the full line command for adding in the user properly. 
that you currently use so people learning to use the software and build do it properly.

also the init scripts are not systemd compatible 

oot@kb3vgw-repeater:/etc/init.d# ./svxlink start
[....] Starting svxlink (via systemctl): svxlink.serviceFailed to start svxlink.service: Unit svxlink.service failed to load: No such file or directory.

I should have them done this week for you . as now that systemd is the default for jessie

**Comment by pe1chl** [comment] 2015-06-04 07:12
Please don't keep hammering on the same issue here in the issue tracker, when you want to discuss something please use the mailinglist.  The issue tracker is (mainly) for registering issues and the steps taken to resolve them.
Do you have difficulties reading English, do you have limited knowledge of Linux, or are there other circumstances that we should know when trying to help you?
It is characteristic for Linux that it is diffucult to almost impossible to provide ready recipes for this because in this area (directory structure, system administration including software installation and user maintenance, service startup) there are differences between Linux distributions and what may be working on Debian may not work on other distributions and probably not even on other Debian versions.
So the instructions are only to the level where you as the installer yourself should be able to pick them up and apply them to the system you have in front of you.  When you cannot do that, you should either learn how to do it, or use prepared binary packages made by people who can.

**Comment by rneese45** [comment] 2015-06-04 12:36
well the new issue with systemd I will move to a diff post as its a diff issue . I have already begun writting/updating the 13.x debian that some one forked off and trying to bring it to par so debian can have pkgs. 

but the systemd missing files will hurt ubuntu and debian and any oither system using the new systemd 

I have figured out the string for making/adding the user for now and have added it to our install script.

**Comment by sm0svx** [comment] 2015-06-06 16:10
Not a bug. Closing issue.

**Closed by sm0svx** 2015-06-06 16:10 UTC
